"""The README's "By the numbers" block, read from the repo and the ledger, never typed. Prints it; --write replaces
the block between the numbers markers in README.md.

  python -m wtdd.numbers            print
  python -m wtdd.numbers --write    write into README.md

Rows are read from the ledger WTDD_LEDGER names (default <repo>/ledger.jsonl). After the table, two lines per shift
(args.shift_id, item 03): its acked_ms values (the on-call person's reply times, from intruder.verdict and
chat.correction rows) with n and the median, or "none" (a WARN); and whether an ok record.signed row closes it
("by <name> at <at>") or "unsigned".
"""
from __future__ import annotations
import json
import statistics
import subprocess
import sys
from pathlib import Path

from .chat.oncall import signed
from .config import ROOT
from .ledger import LEDGER, log, rows as ledger_rows

START, END = "<!-- numbers:start -->", "<!-- numbers:end -->"


def count(pred) -> int:
    f = LEDGER   # honours WTDD_LEDGER (docs/gotchas/03-1)
    return sum(1 for l in f.read_text().splitlines() if l.strip() and pred(l)) if f.exists() else 0


def block() -> str:
    tools = len([p for p in (ROOT / "wtdd" / "tools").glob("*.py") if p.name != "__init__.py"])
    files = subprocess.run(["git", "ls-files", "wtdd/*.py", "ui/index.html"], capture_output=True, text=True, cwd=ROOT).stdout.split()
    lines = sum(len((ROOT / f).read_text().splitlines()) for f in files)
    commits = len(subprocess.run(["git", "log", "--since=2026-09-13 00:00", "--oneline"], capture_output=True, text=True, cwd=ROOT).stdout.splitlines())
    ev = ROOT / "evals.json"
    rows = json.loads(ev.read_text())["rows"] if ev.exists() else []
    n = {
        "external apps, all live": 5,
        "tools, one file each": tools,
        "lines of Python and page": lines,
        "commits, build day": commits,
        "ledger rows, build day": count(lambda l: '"ts": "2026-09-13' in l),
        "light writes with read-back": count(lambda l: '"tool": "lights.set"' in l or '"tool": "lights.tuya_set"' in l),
        "dog commands with state read-back": count(lambda l: '"tool": "dog.cmd"' in l),
        "model calls (each a trace row)": count(lambda l: '"tool": "llm.generate"' in l),
        "posts to the group, each confirmed from chat.db": count(lambda l: '"tool": "chat.post"' in l and '"ok": true' in l and '"kind": "escalate"' not in l),
        "eval trials, graded from device state": f"{len(rows)}, {sum(r['grade'] == 'pass' for r in rows)} pass, {sum(r['grade'] == 'unsafe' for r in rows)} unsafe",
    }
    out = ["| | |", "|---|---|"] + [f"| {k} | {v} |" for k, v in n.items()]
    all_rows = ledger_rows()
    for s in shifts(all_rows):
        acked, sid = s["acked_ms"], s["shift_id"]
        if not acked:
            log("numbers", f"WARN shift {sid}: 0 acked replies", flags=s["flags"])
        sig = signed(sid, all_rows)
        out.append(f"| shift {sid}: acked_ms | " + (f"{', '.join(map(str, acked))} (n={len(acked)}, median {round(statistics.median(acked))})"
                                                  if acked else "none (WARN)") + " |")
        out.append(f"| shift {sid}: signed | " + (f"by {sig['args']['by']} at {sig['args']['at']}" if sig else "unsigned") + " |")
    return "\n".join(out) + "\n\n_Generated by `python -m wtdd.numbers --write` from the repo, `ledger.jsonl` and `evals.json`._"


def shifts(rows: list[dict]) -> list[dict]:
    """Per args.shift_id, sorted: flags (ok escalate posts), acked_ms (ok intruder.verdict / chat.correction rows, ledger
    order, a None skipped), signed and signed_by (the last ok record.signed row; none = unsigned)."""
    out: dict[str, dict] = {}
    for r in rows:
        a = r.get("args") or {}
        if not a.get("shift_id"):
            continue
        s = out.setdefault(a["shift_id"], {"shift_id": a["shift_id"], "flags": 0, "acked_ms": [], "signed": False, "signed_by": None})
        if not r.get("ok"):
            continue
        if r.get("tool") == "chat.post" and a.get("kind") == "escalate":
            s["flags"] += 1
        elif r.get("tool") in ("intruder.verdict", "chat.correction") and a.get("acked_ms") is not None:
            s["acked_ms"].append(a["acked_ms"])
        elif r.get("tool") == "record.signed":
            s["signed"], s["signed_by"] = True, a.get("by")
    return [out[k] for k in sorted(out)]


def main(argv: list[str] | None = None) -> int:
    text = block()
    print(text)
    if "--write" in (argv or sys.argv[1:]):
        p = ROOT / "README.md"; s = p.read_text()
        if START not in s or END not in s:
            raise SystemExit(f"README.md has no {START} / {END} markers")
        p.write_text(s[: s.index(START) + len(START)] + "\n" + text + "\n" + s[s.index(END):])
    return 0


if __name__ == "__main__":
    sys.exit(main())
